# Generated by Django 3.2 on 2021-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittAnalysisService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='twitt',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
