# Generated by Django 3.2 on 2021-06-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittAnalysisService', '0002_auto_20210606_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='public_metrics',
        ),
        migrations.DeleteModel(
            name='ReferencedTwitts',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='twitt',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='PublicMetrics',
        ),
        migrations.DeleteModel(
            name='Twitt',
        ),
    ]
